/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Archivos;

import antenna.AntennaBeastFile;
import antenna.AntennaReceiver;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import de.serosystems.lib1090.Position;

/**
 *
 * @author jorge * >>> CLASE PRINCIPAL (CONTENEDOR) Esta clase es la "ventana"
 * (JFrame) que sostiene todo. Su funcion no es dibujar (eso lo hace
 * RadarPanel), sino: 1. Configurar la fuente de datos (Antenna). 2. Crear la
 * interfaz grafica. 3. Gestionar el ciclo de vida de la app (arrancar/cerrar).
 */
public class RadarFrame extends javax.swing.JFrame {

    // >>> EL BACKEND (La logica de datos)
    // Este objeto 'ar' es el que lee el fichero txt y escupe datos de aviones cada segundo.
    private AntennaReceiver ar;

    // >>> CONFIGURACION "HARDCODEADA"
    // Aqui defines qué mapa y que escenario se cargan al iniciar.
    private final String mapfile = "src/resources/mapa_espana.txt";
    private final String filename = "src/resources/Track2.txt"; // El escenario actual

    // >>> PUNTO DE REFERENCIA
    // Centro del radar (Valencia), necesario para que la antena calcule coordenadas relativas.
    Position vlc = new Position(0.4727777777777778, 39.489444444444445, 4.0);

    public RadarFrame() {

        // >>> 1. CONEXION DE DATOS (ANTENA)
        // Intentamos crear la antena leyendo de un fichero (Simulacion).
        // Si fuera un radar real, usariamos 'AntennaBeast' con una IP.
        try {
            // filename: El archivo de texto con los tramas.
            // vlc: La posición de referencia.
            // null: No usamos decodificador complejo aquí.
            ar = new AntennaBeastFile(filename, vlc, null);
        } catch (IOException ex) {
            // Gestion de errores basica por si el fichero no existe.
            System.out.println("File: " + filename + " not found.");
        }

        // >>> 2. INICIALIZACIÓN VISUAL
        // Llama al metodo generado por NetBeans que coloca los paneles, botones, etc.
        initComponents();

        // Centra la ventana en la pantalla del ordenador.
        this.setLocationRelativeTo(null);

        // >>> 3. ARRANQUE DEL MOTOR
        // Importante: Si la antena se creó bien, hay que decirle "empieza a leer".
        // (Nota: En este código falta el ar.start(), asegúrate de que esté en initComponents
        // o añádelo aquí, si no, los aviones no se moverán).
        if (ar != null) {
            //ar.start(); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radarPanel = new Archivos.RadarPanel(mapfile, ar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        radarPanel.setBackground(new java.awt.Color(0, 0, 0));
        radarPanel.setPreferredSize(new java.awt.Dimension(890, 900));

        javax.swing.GroupLayout radarPanelLayout = new javax.swing.GroupLayout(radarPanel);
        radarPanel.setLayout(radarPanelLayout);
        radarPanelLayout.setHorizontalGroup(
            radarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
        );
        radarPanelLayout.setVerticalGroup(
            radarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(radarPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(radarPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        radarPanel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
// >>> LIMPIEZA DE RECURSOS
    // Este método se ejecuta justo antes de que la ventana desaparezca.
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        ar.stopit();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadarFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        // Arranca la aplicación dentro del hilo gráfico de Java (EDT)
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadarFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel radarPanel;
    // End of variables declaration//GEN-END:variables

}
